# SQL-EX with Postgres

In [3]:
# Install postgresql server
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo service postgresql start

# Setup a password `postgres` for username `postgres`
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 10.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package cron.
(Reading database ... 155673 files and directories currently installed.)
Preparing to unpack .../0-cron_3.0pl1-128.1ubuntu1.2_amd64.deb ...
Unpacking cron (3.0pl1-128.1ubuntu1.2) ...
Selecting previously unselected package logrotate.
Preparing to unpack .../1-logrotate_3.11.0-0.1ubuntu1_amd64.deb ...
Unpacking logrotate (3.11.0-0.1ubuntu1) ...
Selecting previously unselected package netbase.
Preparing to unpack .../2-netbase_5.4_all.deb ...
Unpacking netbase (5.4) ...
Selecting previously unselected

In [4]:
from sqlalchemy import create_engine
con = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/postgres')

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)


Скачиваем данные с sql-ex

In [5]:
!wget https://sql-ex.ru/download/sql-ex-pg.sql

--2022-08-01 11:13:10--  https://sql-ex.ru/download/sql-ex-pg.sql
Resolving sql-ex.ru (sql-ex.ru)... 5.188.73.3, 2a00:ab00:1203:22:ce0:a1ff:fee0:bb42
Connecting to sql-ex.ru (sql-ex.ru)|5.188.73.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41053 (40K) [application/x-sql]
Saving to: ‘sql-ex-pg.sql’

sql-ex-pg.sql       100%[===================>]  40.09K  --.-KB/s    in 0s      

2022-08-01 11:13:11 (190 MB/s) - ‘sql-ex-pg.sql’ saved [41053/41053]



In [6]:
with open('/content/sql-ex-pg.sql', 'r') as file:
    sql = file.read()

Запускаем скрипт

In [7]:
con.execute(sql[1:])

In [8]:
import pandas as pd

In [9]:
def select(sql):
  return pd.read_sql(sql,con)

## Задание: 1
Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 дол. Вывести: model, speed и hd

In [10]:
sql = '''Select DISTINCT model, speed, hd
from pc
WHERE price < 500
'''
select(sql)

model  speed    hd
0  1260    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1232    500  10.0

Теперь напишем сам запрос

## Задание: 2
Найдите производителей принтеров. Вывести: maker

In [11]:
sql = '''
SELECT DISTINCT maker 
FROM PRODUCT as t
where t.type = 'Printer'
'''
select(sql)

maker
0     A
1     D
2     E

## Задание: 3
Найдите номер модели, объем памяти и размеры экранов ПК-блокнотов, цена которых превышает 1000 дол.

In [12]:
sql = '''
SELECT t.model, t.ram, t.screen
FROM laptop as t
WHERE t.price > 1000
'''
select(sql)

model  ram  screen
0  1750  128      14
1  1298   64      15
2  1752  128      14

## Задание: 4
Найдите все записи таблицы Printer для цветных принтеров.

In [13]:
sql = '''
SELECT *
from printer as t
where t.color = 'y'

'''
select(sql)

code model color type  price
0     2  1433     y  Jet  270.0
1     3  1434     y  Jet  290.0

## Задание: 5
Найдите номер модели, скорость и размер жесткого диска ПК, имеющих 12x или 24x CD и цену менее 600 дол.

In [14]:
sql = '''
SELECT t.model, t.speed, t.hd
from pc as t
where t.price < 600 and  t.cd in ('12x', '24x')
'''
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

## Задание: 6
Для каждого производителя, выпускающего ПК-блокноты c объёмом жесткого диска не менее 10 Гбайт, найти скорости таких ПК-блокнотов. Вывод: производитель, скорость.

In [15]:
sql = '''
SELECT distinct p.maker, t.speed
from laptop as t
left join product as p 
on p.model = t.model
where t.hd >= 10
'''
select(sql)

maker  speed
0     A    750
1     A    450
2     A    600
3     B    750

## Задание: 7
Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B (латинская буква).

In [16]:
sql = '''
select distinct t1.model, t2.price
from
    Product as t1 inner join (select model, price
                              from Printer
                              union all
                                      select model, price
                                      from PC
                              union all
                                      select model, price
                                      from laptop) as t2 
on t1.model=t2.model
where maker = 'B'

'''
select(sql)

model   price
0  1121   850.0
1  1750  1200.0

## Задание: 8
Найдите производителя, выпускающего ПК, но не ПК-блокноты.

In [17]:
sql = '''
select distinct p.maker 
from product as p 
where p.type='PC' 
and p.maker not in (select t.maker
                    from product as t
                    where t.type = 'Laptop')
'''
select(sql)

maker
0     E

## Задание: 9
Найдите производителей ПК с процессором не менее 450 Мгц. Вывести: Maker

In [18]:
sql = '''
select distinct p.maker
from product as p
where p.model in 
                (select t.model
                from pc as t
                where speed >= 450)
                

'''
select(sql)

maker
0     B
1     E
2     A

In [19]:
# или еще через Join
sql = '''
select Distinct t2.maker
from PC as t1 inner join Product as t2 on t1.model=t2.model
where speed >= 450
                
'''
select(sql)


maker
0     B
1     E
2     A

## Задание: 10
Найдите модели принтеров, имеющих самую высокую цену. Вывести: model, price

In [20]:
sql = '''
select distinct p.model, p.price
from printer as p
where p.price = (select max(price) as mx from printer as p)
'''
select(sql)

model  price
0  1276  400.0
1  1288  400.0

## Задание: 11
Найдите среднюю скорость ПК.

In [21]:
sql = '''
select avg(t.speed)
from pc as t
'''
select(sql)

avg
0  608.333333

## Задание: 13
Найдите среднюю скорость ПК, выпущенных производителем A.

In [22]:
sql = '''
select avg(t.speed)
from pc as t
join product as p 
on p.model = t.model 
where p.maker = 'A' 
'''
select(sql)

avg
0  606.25

## Задание: 14
Найдите класс, имя и страну для кораблей из таблицы Ships, имеющих не менее 10 орудий.

In [23]:
sql = '''
select cl.class, t.name, cl.country
from ships as t
join classes as cl 
on cl.class = t.class
where numguns >=10 
'''
select(sql)

class            name country
0       Tennessee      California     USA
1  North Carolina  North Carolina     USA
2       Tennessee       Tennessee     USA
3  North Carolina      Washington     USA
4  North Carolina    South Dakota     USA

## Задание: 15
Найдите размеры жестких дисков, совпадающих у двух и более PC. Вывести: HD

In [24]:
sql = '''
select t.hd
from pc as t
group by t.hd 
having count(*) > 1
'''
select(sql)

hd
0   8.0
1  20.0
2   5.0
3  14.0
4  10.0

## Задание: 16
Найдите пары моделей PC, имеющих одинаковые скорость и RAM. В результате каждая пара указывается только один раз, т.е. (i,j), но не (j,i), Порядок вывода: модель с большим номером, модель с меньшим номером, скорость и RAM.

In [25]:
sql = '''
select Distinct A.model, B.model, a.speed, a.ram
from pc as a, pc as b
where a.speed = b.speed and a.ram=b.ram and a.model > b.model
'''
select(sql)

model model  speed  ram
0  1233  1121    750  128
1  1233  1232    500   64
2  1260  1232    500   32

## Задание: 17
Найдите модели ПК-блокнотов, скорость которых меньше скорости каждого из ПК.
Вывести: type, model, speed

In [26]:
sql = '''
select distinct  'Laptop' as type, t.model, t.speed
from laptop as t
where t.speed < (select min(pc.speed) from pc )
'''
select(sql)

type model  speed
0  Laptop  1298    350

## Задание: 18
Найдите производителей самых дешевых цветных принтеров. Вывести: maker, price

In [27]:
sql = '''
select distinct  p.maker, t.price
from printer as t
join product as p 
on p.model = t.model
where t.price = (select min(t.price)
      from printer as t
      where t.color = 'y')
and t.color = 'y'
'''
select(sql)

maker  price
0     D  270.0

## Задание: 19
Для каждого производителя, имеющего модели в таблице Laptop, найдите средний размер экрана выпускаемых им ПК-блокнотов.
Вывести: maker, средний размер экрана.

In [28]:
sql = '''
select p.maker, avg(t.screen) as avg_screen
from laptop as t
join product as p 
on p.model = t.model
group by p.maker

'''
select(sql)

maker  avg_screen
0     B        14.0
1     C        12.0
2     A        13.0

## Задание: 20
Найдите производителей, выпускающих по меньшей мере три различных модели ПК. Вывести: Maker, число моделей ПК.

In [29]:
sql = '''
select t.maker, count(*) as cnt_models
from product as t
where type= 'PC'
group by t.maker
having count(*)> 2 

'''
select(sql)

maker  cnt_models
0     E           3

## Задание: 21
Найдите максимальную цену ПК, выпускаемых каждым производителем, у которого есть модели в таблице PC.
Вывести: maker, максимальная цена.

In [30]:
sql = '''
select p.maker, max(t.price) as max_price
from pc as t
left join product as p 
on p.model =t.model 
group by p.maker

'''
select(sql)

maker  max_price
0     B      850.0
1     E      350.0
2     A      980.0

## Задание: 22
Для каждого значения скорости ПК, превышающего 600 МГц, определите среднюю цену ПК с такой же скоростью. Вывести: speed, средняя цена.

In [31]:
sql = '''
select t.speed, avg(t.price) as avg_price_600
from pc as t
where t.speed > 600
group by t.speed 

'''
select(sql)

speed  avg_price_600
0    900          980.0
1    750          900.0
2    800          970.0

## Задание: 23
Найдите производителей, которые производили бы как ПК
со скоростью не менее 750 МГц, так и ПК-блокноты со скоростью не менее 750 МГц.
Вывести: Maker

In [32]:
# быть осторожным нужно именно пересечение что бы производитель выпускал и тот и другой продукт
sql = '''
Select distinct maker 
from Laptop as t1 left join Product as t2 on t1.model=t2.model
where t1.speed >=750 
INTERSECT 
Select distinct maker 
from PC as t1 left join Product as t2 on t1.model=t2.model
where t1.speed >=750 
'''
select(sql)

maker
0     B
1     A

## Задание: 24
Перечислите номера моделей любых типов, имеющих самую высокую цену по всей имеющейся в базе данных продукции.

In [33]:

sql = '''
with tab as 
           ( Select p.model, p.price
            from pc as p
            union all
            Select l.model, l.price
            from laptop as l
            union all
            Select pr.model, pr.price
            from printer as pr)
select distinct tab.model 
from tab 
where price = (select max(price) as max_price from tab)
'''
select(sql)

model
0  1750

## Задание: 25
Найдите производителей принтеров, которые производят ПК с наименьшим объемом RAM и с самым быстрым процессором среди всех ПК, имеющих наименьший объем RAM. Вывести: Maker

In [34]:

sql = '''
select distinct t.maker 
from product as t 
where t.model in 
                  (select model
                  from pc as t
                  where ram = (select min(ram) from pc)
                  and speed = (select max(speed) 
                              from pc 
                              where ram = (select min(ram) from pc)))
and t.maker in (select distinct t.maker
                from product as t
                where t.type = 'Printer')
'''
select(sql)

maker
0     A
1     E

## Задание: 26
Найдите среднюю цену ПК и ПК-блокнотов, выпущенных производителем A (латинская буква). Вывести: одна общая средняя цена.

In [35]:
# Следует учесть, что UNION исключает дубликаты, что приведет к потере данных и соответсвенно неврного расчета среднего
sql = '''
select avg(price) as avg_price
from
    (select t.model, t.price
    from laptop as t
    union 
    select t.model, t.price
    from pc as t) as t
join product as p 
on p.model = t.model
where p.maker = 'A'
'''
select(sql)

avg_price
0  790.909091

## Задание: 27
Найдите средний размер диска ПК каждого из тех производителей, которые выпускают и принтеры. Вывести: maker, средний размер HD.

In [36]:

sql = '''
select p.maker, avg(t.hd) as avg_hd
from pc as t 
join product as p 
on p.model = t.model
where p.maker in (select distinct maker
                  from product as p
                  where p.type =  'Printer')
group by p.maker 
'''
select(sql)

maker  avg_hd
0     A   14.75
1     E   10.00

## Задание: 28
Используя таблицу Product, определить количество производителей, выпускающих по одной модели.

In [37]:
sql = '''
select count(*)
from
    (select t.maker, count(distinct model) as cnt_models
    from product as t
    group by t.maker 
    having count(distinct model)= 1) as tab
'''
select(sql)

count
0      1

## Задание: 29
В предположении, что приход и расход денег на каждом пункте приема фиксируется не чаще одного раза в день [т.е. первичный ключ (пункт, дата)], написать запрос с выходными данными (пункт, дата, приход, расход). Использовать таблицы Income_o и Outcome_o.

In [38]:
# важно понмать что может быть день когда небыло прихода или наоборот когда не было расхода
sql = '''
select t1.point, t1.date, inc, out
from
(Select distinct point, date
from Outcome_o
UNION
Select point, date
from Income_o) as t1 
left join Income_o as t2 
    on t1.point=t2.point and t1.date=t2.date
left join Outcome_o as t3 
    on t1.point=t3.point 
'''
select(sql)

point       date      inc      out
0        1 2001-03-23  15000.0  15348.0
1        1 2001-04-13   5000.0  15348.0
2        1 2001-05-11   4500.0  15348.0
3        1 2001-03-22  15000.0  15348.0
4        1 2001-03-29      NaN  15348.0
..     ...        ...      ...      ...
118      3 2001-10-02  18000.0   2300.0
119      3 2001-09-13  11500.0   2150.0
120      3 2001-09-14      NaN   2150.0
121      3 2002-09-16      NaN   2150.0
122      3 2001-10-02  18000.0   2150.0

[123 rows x 4 columns]

## Задание: 30
В предположении, что приход и расход денег на каждом пункте приема фиксируется произвольное число раз (первичным ключом в таблицах является столбец code), требуется получить таблицу, в которой каждому пункту за каждую дату выполнения операций будет соответствовать одна строка.
Вывод: point, date, суммарный расход пункта за день (out), суммарный приход пункта за день (inc). Отсутствующие значения считать неопределенными (NULL).

In [39]:
# важно понмать что может,
# что при джойне можно задвоить суммы нужно обязательно джойнить не просто по дате и  точке, а так же по code
sql = '''
with t as 
        (select code, point,	date
        from  outcome 
        union
        select code, point,	date
        from income) 
select t.point, t.date , sum(out) as out, sum(inc) as inc 
from t
left join outcome as o ON o.point= t.point and o.date=t.date and o.code = t.code
left join income as i ON i.point= t.point and i.date=t.date and i.code = t.code
group by t.point, t.date
'''
select(sql)

point       date       out      inc
0       1 2001-04-11   3195.04      NaN
1       1 2001-03-23       NaN  15000.0
2       1 2001-03-22       NaN  30000.0
3       1 2001-03-26   1221.00      NaN
4       1 2001-03-29   4010.00      NaN
5       3 2001-09-13   2700.00   3100.0
6       1 2001-03-28   2075.00      NaN
7       1 2001-03-14  15348.00      NaN
8       2 2001-03-29   7848.00      NaN
9       1 2001-04-13   4490.00  10000.0
10      1 2001-03-24   7163.00   7000.0
11      1 2001-05-11   2530.00   4500.0
12      2 2001-03-24       NaN   3000.0
13      3 2001-09-14   1150.00      NaN
14      2 2001-04-02   2040.00      NaN
15      1 2001-04-27   3110.00      NaN
16      2 2001-03-22   2880.00  10000.0

## Задание: 31
Для классов кораблей, калибр орудий которых не менее 16 дюймов, укажите класс и страну.

In [40]:

sql = '''
select t.class,t.country
from classes as t
where t.bore >= 16
'''
select(sql)

class country
0            Iowa     USA
1  North Carolina     USA
2          Yamato   Japan

## Задание: 32
Одной из характеристик корабля является половина куба калибра его главных орудий (mw). С точностью до 2 десятичных знаков определите среднее значение mw для кораблей каждой страны, у которой есть корабли в базе данных.

In [41]:

sql = '''
select country, cast(avg(bore*bore*bore/2) as numeric(38,2)) 
from
    (select country, name, bore 
      from ships as sh 
      join classes c 
      on sh.class=c.class
    union
      select country, ship, bore 
      from outcomes as o 
      join classes c on o.ship = c.class) t1
group by country

'''
select(sql)

country      avg
0         USA  1897.78
1     Germany  1687.50
2  Gt.Britain  1687.50
3       Japan  1886.67

## Задание: 33
Укажите корабли, потопленные в сражениях в Северной Атлантике (North Atlantic). Вывод: ship.

In [42]:

sql = '''
select t.ship
from outcomes as t 
where t.battle = 'North Atlantic' and result='sunk'
'''
select(sql)

ship
0  Bismarck
1      Hood

## Задание: 34
По Вашингтонскому международному договору от начала 1922 г. запрещалось строить линейные корабли водоизмещением более 35 тыс.тонн. Укажите корабли, нарушившие этот договор (учитывать только корабли c известным годом спуска на воду). Вывести названия кораблей.

In [43]:

sql = '''
Select distinct name
from ships as t1 
join classes as t2 
on t1.class=t2.class
where launched >= 1922
and displacement > 35000 
and type = 'bb'
'''
select(sql)

name
0            Iowa
1        Missouri
2         Musashi
3      New Jersey
4  North Carolina
5    South Dakota
6      Washington
7       Wisconsin
8          Yamato

## Задание: 35
В таблице Product найти модели, которые состоят только из цифр или только из латинских букв (A-Z, без учета регистра).
Вывод: номер модели, тип модели.

In [44]:

sql = '''
Select t.model, t.type
from product  as t
WHERE t.model SIMILAR TO '[0-9]+' OR t.model SIMILAR TO '[a-zA-Z]+'
'''
select(sql)

model     type
0   1121       PC
1   1232       PC
2   1233       PC
3   1260       PC
4   1276  Printer
5   1288  Printer
6   1298   Laptop
7   1321   Laptop
8   1401  Printer
9   1408  Printer
10  1433  Printer
11  1434  Printer
12  1750   Laptop
13  1752   Laptop
14  2113       PC
15  2112       PC

## Задание: 36
Перечислите названия головных кораблей, имеющихся в базе данных (учесть корабли в Outcomes).

In [45]:
sql = '''
select cl.class
from 
      (SELECT ship FROM Outcomes
      except 
      select name from ships
      union
      select name from ships) as t
join classes as cl on cl.class = t.ship
'''

select(sql)

class
0          Yamato
1        Bismarck
2         Revenge
3  North Carolina
4       Tennessee
5           Kongo
6          Renown
7            Iowa

## Задание: 37
Найдите классы, в которые входит только один корабль из базы данных (учесть также корабли в Outcomes).

In [46]:
sql = '''
SELECT c.class
FROM classes c
LEFT JOIN (
            SELECT class, name
            FROM ships
          UNION
            SELECT ship, ship
            FROM outcomes) AS s 
ON s.class = c.class
GROUP BY c.class
HAVING COUNT(s.name) = 1
'''

select(sql)

class
0  Bismarck

## Задание: 38
Найдите страны, имевшие когда-либо классы обычных боевых кораблей ('bb') и имевшие когда-либо классы крейсеров ('bc').

In [47]:
sql = '''
SELECT  t.country
from classes as t
group by t.country
having count(distinct t.type) >1
'''
select(sql)

country
0  Gt.Britain
1       Japan

In [48]:
sql = '''
SELECT  t.country
from classes as t
group by t.country
having count(distinct t.type) >1
'''
select(sql)

country
0  Gt.Britain
1       Japan

## Задание: 39
Найдите корабли, `сохранившиеся для будущих сражений`; т.е. выведенные из строя в одной битве (damaged), они участвовали в другой, произошедшей позже.

In [49]:
sql = '''

WITH t1 as
(SELECT o.ship, b.name, o.result, b.date
FROM outcomes as O
LEFT JOIN battles as B ON O.battle=B.name)

SELECT DISTINCT a.ship 
FROM t1 as a
WHERE a.ship in 
	       (select ship from t1 as b
	       where b.date < a.date and b.result = 'damaged')
'''
select(sql)

ship
0  California

In [50]:
sql = '''
select distinct t.ship
from
(SELECT *, case when o.result = 'damaged' then count(*) over (partition by o.ship order by b.date rows between current row and unbounded following) else 0 end as cnt
  FROM outcomes as o
  LEFT JOIN battles as b ON o.battle=b.name
  order by b.date ) as t
where t.cnt > 1
'''
select(sql)

ship
0  California

In [51]:
sql = '''
with t as 
(SELECT ship, result, date
from outcomes as o
LEFT JOIN battles as b ON o.battle=b.name)

select distinct t1.ship
from t as t1
where result = 'damaged'
and exists (select * from t where t1.ship = t.ship and t1.date < t.date)
'''
select(sql)

ship
0  California

## Задание: 40
Найти производителей, которые выпускают более одной модели, при этом все выпускаемые производителем модели являются продуктами одного типа.
Вывести: maker, type

In [52]:
sql = '''
select distinct maker, type
from product as p
where p.maker in  
									(select t.maker 
									from product as t
									group by t.maker
									having count(t.model) > 1 and  count(distinct t.type) = 1  )
'''
select(sql)

maker     type
0     D  Printer

## Задание: 41
Для каждого производителя, у которого присутствуют модели хотя бы в одной из таблиц PC, Laptop или Printer,
определить максимальную цену на его продукцию.
Вывод: имя производителя, если среди цен на продукцию данного производителя присутствует NULL, то выводить для этого производителя NULL,
иначе максимальную цену.

In [53]:
sql = '''
with t as 
				(select model, price from pc
				union 
				select model, price from printer
				union 
				select model, price from laptop),

t2 as (select *
from product as p
join t 
on t.model = p.model)

select maker, CASE WHEN maker IN (SELECT DISTINCT maker FROM t2 WHERE price IS NULL) THEN NULL ELSE MAX(price) END as max_price
from t2
group by maker
'''
select(sql)

maker  max_price
0     B     1200.0
1     C      970.0
2     D      400.0
3     E      350.0
4     A     1150.0

## Задание: 42
Найдите названия кораблей, потопленных в сражениях, и название сражения, в котором они были потоплены.

In [54]:
sql = '''
SELECT o.ship, o.battle
FROM outcomes as o
where o.result = 'sunk'
'''
select(sql)

ship          battle
0    Bismarck  North Atlantic
1        Fuso  Surigao Strait
2        Hood  North Atlantic
3   Kirishima     Guadalcanal
4  Schamhorst      North Cape
5   Yamashiro  Surigao Strait

## Задание: 43
Укажите сражения, которые произошли в годы, не совпадающие ни с одним из годов спуска кораблей на воду.

In [55]:
sql = '''
select b.name 
from battles as b
where not exists (select s.launched 
                  from ships as s 
                  where extract(year from b.date) = s.launched)
'''
select(sql)

name
0  #Cuba62a
1  #Cuba62b

## Задание: 44
Найдите названия всех кораблей в базе данных, начинающихся с буквы R.

In [56]:
sql = '''
select t.name 
from ships as t
where t.name SIMILAR TO '[R]_+'
union 
select t.ship 
from outcomes as t
where t.ship SIMILAR TO '[R]_+'
'''
select(sql)

name
0        Ramillies
1           Renown
2          Repulse
3       Resolution
4          Revenge
5           Rodney
6        Royal Oak
7  Royal Sovereign

## Задание: 45
Найдите названия всех кораблей в базе данных, состоящие из трех и более слов (например, King George V).
Считать, что слова в названиях разделяются единичными пробелами, и нет концевых пробелов.

In [57]:
sql = '''
SELECT ship FROM (
     SELECT ship FROM outcomes
     UNION
     SELECT name FROM Ships
     ) t
WHERE ship ~ '\S+\s\S+\s';
'''
select(sql)

ship
0  Prince of Wales
1    King George V
2     Duke of York

## Задание: 46
Для каждого корабля, участвовавшего в сражении при Гвадалканале (Guadalcanal), вывести название, водоизмещение и число орудий.

In [58]:
sql = '''
SELECT o.ship, displacement, numGuns
FROM outcomes o 
LEFT  JOIN 
        (SELECT s.name AS ship, displacement, numGuns
        FROM ships s
        JOIN classes c ON c.class= s.class
union
        SELECT c.class AS ship, displacement, numGuns
        FROM classes c) AS t ON o.ship=t.ship
        WHERE battle='Guadalcanal'


'''
select(sql)

ship  displacement  numguns
0    California         32000       12
1    Washington         37000       12
2     Kirishima         32000        8
3  South Dakota         37000       12

## Задание: 47
Определить страны, которые потеряли в сражениях все свои корабли.

In [59]:
sql = '''
-- таблица всех кораблей и их классов
select cl.country
from classes as cl
join  (select s.name, s.class
            from ships as s
            union
            select o.ship, o.ship
            from outcomes as o) as t
on t.class = cl.class
full join outcomes as o
on o.ship = t.name
where cl.country is not null
group by cl.country
having count(distinct t.name) = sum(case when o.result = 'sunk' then 1 else 0 end)

'''
select(sql)

country
0  Germany

In [60]:
sql = '''
-- таблица всех кораблей и их классов
with all_ships as
            (select s.name, s.class
            from ships as s
            union
            select o.ship, o.ship
            from outcomes as o),

-- таблица всех странн и количество кораблей в этой стране
tab_all as (select cl.country, count(*) as cnt_all
from all_ships  as t
left join classes as cl
on cl.class = t.class 
where cl.country is not null
group by cl.country ),

-- таблица кораблей и их классов который были уничтожены во время сражений
all_sunk as (select o.ship, case when t.class is null then o.ship else t.class end as class
from outcomes as o
left join  all_ships as t on o.ship = t.name 
where o.result = 'sunk'	),

-- таблица всех странн и количество уничтоженных кораблей в этой стране
tab_sunk as (select cl.country, count(*) as cnt_sunk
from all_sunk as t
left join classes as cl 
on cl.class = t.class 
where cl.country is not null
group by cl.country)

select a.country
from  tab_all as a
left join tab_sunk as b on a.country = b.country
where a.cnt_all=b.cnt_sunk
'''
select(sql)

country
0  Germany

In [61]:
sql = '''
with t as (select ship as name , ship as class
	from classes as c
	left join outcomes as o on o.ship=c.class
	where o.ship is not null
	union
	select name, class
	from ships),

t2 as (select t.name, t.class, country	
from t
left join outcomes as o on o.ship=t.name
left join classes as c on c.class = t.class)


select t3.country
from 
(select country, count(distinct name) as cnt
from t2
left join outcomes as o on o.ship = t2.name
group by country) as t3
join 
(select  country, count(distinct name) as cnt
from t2
left join outcomes as o on o.ship = t2.name
where result = 'sunk'
group by country) as t4  on t3.country=t4.country
where t3.cnt=t4.cnt


'''
select(sql)

country
0  Germany

## Задание: 48

Найдите классы кораблей, в которых хотя бы один корабль был потоплен в сражении.

In [62]:
sql = '''
SELECT distinct cl.class
FROM Classes cl
LEFT JOIN Ships s 
ON s.class = cl.class
where cl.class in (select ship from outcomes where result='sunk')
or s.name in (select ship from outcomes where result='sunk')


'''
select(sql)

class
0  Bismarck
1     Kongo

## Задание: 49

Найдите названия кораблей с орудиями калибра 16 дюймов (учесть корабли из таблицы Outcomes).

In [63]:
sql = '''
select ship
from 
	classes as cl
join 
    (select ship, ship as class
    from outcomes as o 
	union
    select s.name, s.class  
    from ships as s) as t
on cl.class = t.class
where cl.bore = 16

'''
select(sql)

ship
0      Washington
1    South Dakota
2            Iowa
3       Wisconsin
4  North Carolina
5      New Jersey
6        Missouri

## Задание: 50

Найдите сражения, в которых участвовали корабли класса Kongo из таблицы Ships.

In [64]:
sql = '''
select distinct o.battle
from outcomes as o 
where o.ship in (
                select s.name
                from  ships as s
                where s.class = 'Kongo'
                )

'''
select(sql)

battle
0  Guadalcanal

## Задание: 51

Найдите названия кораблей, имеющих наибольшее число орудий среди всех имеющихся кораблей такого же водоизмещения (учесть корабли из таблицы Outcomes).

In [65]:
sql = '''
with tab as 
(select t.name, cl.class, cl.numGuns, cl.displacement
from 
(select name, class
from ships
union 
select ship, ship
from outcomes) as t
join classes as cl on cl.class = t.class),

--
dag as 
(select displacement, 
max(numGuns) as max
from tab 
group by displacement)


select name
from tab 
where exists (select * 
              from dag 
              where tab.numGuns = max 
              and tab. displacement =  displacement)

'''
select(sql)

name
0          Bismarck
1        Washington
2      South Dakota
3         Tennessee
4         Royal Oak
5           Musashi
6   Royal Sovereign
7        California
8              Iowa
9         Ramillies
10          Revenge
11        Wisconsin
12   North Carolina
13       New Jersey
14           Yamato
15         Missouri

## Задание: 52

Определить названия всех кораблей из таблицы Ships, которые могут быть линейным японским кораблем,
имеющим число главных орудий не менее девяти, калибр орудий менее 19 дюймов и водоизмещение не более 65 тыс.тонн

In [66]:
sql = '''
select s.name 
from ships as s
join classes as c on c.class = s.class
where   (c.type ='bb')
	AND (c.country = 'Japan')
  AND (numguns>=9 or numGuns is NULL)
	AND (c.bore < 19 OR c.bore IS NULL)
	AND (displacement <= 65000 OR c.displacement IS NULL)

'''
select(sql)

name
0  Musashi
1   Yamato

## Задание: 53

Определите среднее число орудий для классов линейных кораблей.
Получить результат с точностью до 2-х десятичных знаков.

In [67]:
sql = '''
select Cast(avg(c.numGuns ) as numeric (15, 2)) as avg
from classes as c
where c.type = 'bb' 
'''
select(sql)

avg
0  9.67

In [68]:
sql = '''
select round(avg(c.numGuns *1.0),2) as avg
from classes as c
where c.type = 'bb' 
'''
select(sql)

avg
0  9.67

## Задание: 54

С точностью до 2-х десятичных знаков определите среднее число орудий всех линейных кораблей (учесть корабли из таблицы Outcomes).

In [69]:
sql = '''
select round(avg(numguns * 1.0),2)
from classes as cl
join (select ship, ship as class
    from outcomes 
    union 
    select name, class
    from ships) as t 
on t.class = cl.class
where cl.type = 'bb'
'''
select(sql)

round
0   9.63

In [70]:
sql = '''
select cast(avg(numGuns*1.0) as numeric(30,2)) as avg
from 
(select ship, (case when class is null then ship else class end) as clas
from 
(SELECT ship
from outcomes
union
select name
from ships) as t
left join ships as s on s.name=t.ship) as t2
left join classes as c on c.class = t2.clas
where type = 'bb'
'''
select(sql)



avg
0  9.63

## Задание: 55

Для каждого класса определите год, когда был спущен на воду первый корабль этого класса. Если год спуска на воду головного корабля неизвестен, определите минимальный год спуска на воду кораблей этого класса. Вывести: класс, год.

In [71]:
sql = '''
select cl.class, min(s.launched)
from classes as cl
left join 
    (select name, class
    from ships
    union 
    select ship, ship
    from outcomes) as t on t.class = cl.class
left join ships as s on s.name = t.name 
group by cl.class 
'''
select(sql)

class     min
0       Tennessee  1920.0
1          Yamato  1941.0
2        Bismarck     NaN
3         Revenge  1916.0
4           Kongo  1913.0
5          Renown  1916.0
6  North Carolina  1941.0
7            Iowa  1943.0

In [72]:
sql = '''
select c.class, t3.min
from classes as c 
left join 
(select class, min(launched) as min
from
(select distinct (case when class is null then t.name else class end) as class, launched
from 
    (select name from ships
    union
    select ship from outcomes) as t
left join ships as s on s.name=t.name) as t2
group by class) as t3 on t3.class=c.class
'''
select(sql)

class     min
0        Bismarck     NaN
1            Iowa  1943.0
2           Kongo  1913.0
3  North Carolina  1941.0
4          Renown  1916.0
5         Revenge  1916.0
6       Tennessee  1920.0
7          Yamato  1941.0

## Задание: 56

Для каждого класса определите число кораблей этого класса, потопленных в сражениях. Вывести: класс и число потопленных кораблей.

In [73]:
sql = '''
select c.class , count(t1.ship) as cnt
from classes as c 
left join 
(select ship, class
from outcomes as c
left join ships as s on s.name = c.ship
where result = 'sunk') as t1 
on t1.ship = c.class or t1.class=c.class
group by c.class

'''
select(sql)

class  cnt
0       Tennessee    0
1          Yamato    0
2        Bismarck    1
3         Revenge    0
4           Kongo    1
5          Renown    0
6  North Carolina    0
7            Iowa    0

## Задание: 57

Для классов, имеющих потери в виде потопленных кораблей и не менее 3 кораблей в базе данных, вывести имя класса и число потопленных кораблей.

In [74]:
sql = '''
-- список названий кораблей и их классы
with t  as (select s.name, s.class
from ships as s
union 
select o.ship,o.ship
from outcomes as o),
-- список классов у которых не менее 3х кораблей
t2 as 
    (select t.class, count(t.name) as cnt
    from t
    group by t.class 
    having count(t.name) >=3),
-- список классов у которых и количетсво потопленных кораблей
t3 as (select t.class, count(distinct t.name)
from t 
left join outcomes as o on o.ship = t.name
where result ='sunk'
group by t.class)
select distinct t2.class, t3.count
from t2
join t3 on t2.class = t3.class
'''
select(sql)

class  count
0  Kongo      1

In [75]:
sql = '''
select class, SUM(CASE WHEN result='sunk' THEN 1 ELSE 0 END) as sunks
from (select c.class, name from classes c
      join ships s on c.class=s.class
    union
      select class, ship from classes 
      join outcomes on class=ship
     ) as sh
left join outcomes o on sh.name=o.ship
group by class
having
    SUM(CASE WHEN result='sunk' THEN 1 ELSE 0 END) > 0
    and (select count(si.name) from (
            select s.name, s.class from ships s
            union
            select o.ship, o.ship from outcomes o
          ) as si
        where si.class = sh.class
        group by si.class
        )>=3
-- 1.получаем классы и количество потопленных кораблей, для этого
-- сначала получаем список кораблей с классом, из таблиц Ships и outcomes
-- так как в outcomes есть корабли которых нет в ships то и класс присваиваем
-- по названию и после через union получаем список класс-корабль
'''
select(sql)

class  sunks
0  Kongo      1

## Задание: 58

Для каждого типа продукции и каждого производителя из таблицы Product c точностью до двух десятичных знаков найти процентное отношение числа моделей данного типа данного производителя к общему числу моделей этого производителя.
Вывод: maker, type, процентное отношение числа моделей данного типа к общему числу моделей производителя

In [76]:
sql = '''
--список всех возможных производителей и типа продукции
with t as (select p.maker,p2.type
from product as p
cross join product as p2
group by p.maker,p2.type ),
--список производителяи и типов продукции и количество моделей в ней
t2 as (select maker,type, count(model) as cnt_model
from product as p
group by maker,type)

select t.maker,t.type, cast( case when t2.cnt_model is null then 0 else t2.cnt_model end *100 / sum(t2.cnt_model) over (partition by t.maker order by t.maker) as numeric(18,2)) as share
from t
left join t2 on t.maker = t2.maker and t.type=t2.type
'''
select(sql)

maker     type   share
0      A   Laptop   28.57
1      A       PC   28.57
2      A  Printer   42.86
3      B   Laptop   50.00
4      B       PC   50.00
5      B  Printer    0.00
6      C   Laptop  100.00
7      C       PC    0.00
8      C  Printer    0.00
9      D   Laptop    0.00
10     D       PC    0.00
11     D  Printer  100.00
12     E   Laptop    0.00
13     E       PC   75.00
14     E  Printer   25.00

In [77]:
sql = '''
--список всех возможных производителей и типа продукции
select  maker,
	type,
 	CAST(cnt*100.0 / sum(cnt) over (partition by maker order by maker) as numeric(18,2)) as share
from
(select 
	t1.maker, 
	t1.type,
	case when cnt is null then 0 else cnt end as cnt
from
	(select  p.maker, pp.type
	from product as p
	CROSS join product as pp
	group by p.maker, pp.type) as t1
left join 
	(select maker, type, count(*) as cnt
	from product 
	group by maker, type) as t2
on t2.maker =t1.maker and t2.type=t1.type) as t3

'''
select(sql)

maker     type   share
0      A   Laptop   28.57
1      A       PC   28.57
2      A  Printer   42.86
3      B   Laptop   50.00
4      B       PC   50.00
5      B  Printer    0.00
6      C   Laptop  100.00
7      C       PC    0.00
8      C  Printer    0.00
9      D   Laptop    0.00
10     D       PC    0.00
11     D  Printer  100.00
12     E   Laptop    0.00
13     E       PC   75.00
14     E  Printer   25.00

## Задание: 59

Посчитать остаток денежных средств на каждом пункте приема для базы данных с отчетностью не чаще одного раза в день. Вывод: пункт, остаток.

In [78]:
sql = '''
select c1,  (COALESCE (c2, 0) - COALESCE (o2, 0) ) as balance
from
	(SELECT point c1, sum(inc) c2 FROM income_o
	group by point) as t1
left join
	(SELECT point o1, sum(out) o2 FROM outcome_o
	group by point) as t2
on c1=o1


'''
select(sql)

c1   balance
0   3  23550.00
1   2    172.00
2   1   5263.96

## Задание: 60

Посчитать остаток денежных средств на начало дня 15/04/01 на каждом пункте приема для базы данных с отчетностью не чаще одного раза в день. Вывод: пункт, остаток.
Замечание. Не учитывать пункты, информации о которых нет до указанной даты.

In [79]:
sql = '''
select c1,  c2 -(CASE WHEN o2 is null THEN 0 ELSE o2 END)
from
	(SELECT point c1, sum(inc) c2 FROM income_o
	where date < '2001-04-15 00:00:00.000'
	group by point) as t1
left join
	(SELECT point o1, sum(out) o2 FROM outcome_o
	where date < '2001-04-15 00:00:00.000'
	group by point) as t2
on c1=o1
'''
select(sql)

c1  ?column?
0   2    172.00
1   1   6403.96